I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 529, in script
    python hide:
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 529, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 529, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 540, in _execute_python_hide
    renpy.load(renpy.session["_reload_slot"])
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\28129\\AppData\\Roaming/RenPy/PPTTest-1699512934/sync\\_reload-1-LT1.save'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 529, in script
    python hide:
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "renpy/common/00start.rpy", line 212, in script call
    call _load_reload_game from _call__load_reload_game_1
  File "renpy/common/00keymap.rpy", line 529, in script
    python hide:
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 529, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 540, in _execute_python_hide
    renpy.load(renpy.session["_reload_slot"])
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\loadsave.py", line 810, in load
    log_data, signature = location.load(filename)
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\savelocation.py", line 520, in load
    return l.load(slotname) # type: ignore
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\savelocation.py", line 284, in load
    with zipfile.ZipFile(filename, "r") as zf:
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/zipfile.py", line 1239, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\28129\\AppData\\Roaming/RenPy/PPTTest-1699512934/sync\\_reload-1-LT1.save'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
PPT Test 1.0
Tue Nov 14 19:47:48 2023
